config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root "posts#index"
  get "delete_friend", to: "friends#destroy"
  resources :posts
  resources :users
  resources :comments
  resources :likes
  resources :friends
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :users_comment, through: :comments, class_name: :User
  has_many :users_like, through: :likes, class_name: :User

  scope :load_info, ->{select(:title, :created_at, :user_id, :id).includes(:user)
    .order updated_at: :desc}
  scope :load_friend_post, ->a{select(:title, :created_at, :user_id, :id)
    .includes(:user).where(user_id: a).order updated_at: :desc}
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.load_info.page(params[:page]).per Settings.size
    if user_signed_in?
      @friend_id = Friend.user_id_friend(current_user.id)
        .or(Friend.friend_id_friend(current_user.id))
      friend_id_arr = []
      @friend_id.each do |x|

        if x.user_id != current_user.id
          friend_id_arr.push(x.user_id)
        elsif x.friend_id != current_user.id
          friend_id_arr.push(x.friend_id)
        end
      end
      @posts_friend = Post.load_friend_post(friend_id_arr).page(params[:page]).per Settings.size
    end
  end

  def show
    @post = Post.includes(:user).find_by(id: params[:id])

    if @post
      if user_signed_in?
        find_friendship current_user.id, @post.user.id
      end
      @comments = Comment.load_comment(params[:id]).page(params[:page]).per Settings.size
      @comment = current_user.comments.build if user_signed_in?
    else
      flash[:success] = t "post_error"
      redirect_to root_path
    end
  end

  def new
    @post = current_user.posts.build if user_signed_in?
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t "post_success"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit :title, :content
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="col-xs-12 nopadding comment">
  <div class="col-xs-12 nopadding">
    <% if user_signed_in? %>
      <% if c.user.id == current_user.id %>
        <div class="col-xs-1 nopadding pull-right">
          <div class="col-xs-6 nopadding">
            <%= link_to edit_comment_path(c.id), remote: true do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          </div>
          <div class="col-xs-6 nopadding">
            <%= link_to (c), method: :delete, data: {confirm: t(".sure")}, remote: true do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-12 nopadding user-comment">
    <div class="col-xs-8 nopadding">
      <%= image_tag c.user.avatar.url, class: "img-circle", width: 30, height: 30 %>
      <%= c.user.email %>
    </div>
    <div class="col-xs-3">
      <%= time_ago_in_words(c.created_at) %>
    </div>
  </div>
  <div class="col-xs-12" id="comment_<%= c.id %>">
    <%= c.content %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :content %>
  </div>
  <div>
    <%= f.cktext_area :content, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_friend.html.erb
<div class="col-xs-12">
  <% if @friend == t(".add_friend") %>
    <%= form_tag friends_path, method: :post, remote: true do %>
      <%= hidden_field_tag :post_id, @post.id %>
      <%= hidden_field_tag :friend_id, @post.user.id %>
      <%= submit_tag @friend, class: "btn btn-primary" %>
    <% end %>
  <% elsif @friend == t(".accept_friend") %>
    <%= form_tag friend_path, method: :put, remote: true do %>
      <%= hidden_field_tag :post_id, @post.id %>
      <%= hidden_field_tag :friend_id, @post.user.id %>
      <%= submit_tag @friend, class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <%= form_tag delete_friend_path, method: :get, remote: true do %>
      <%= hidden_field_tag :post_id, @post.id %>
      <%= hidden_field_tag :friend_id, @post.user.id %>
      <%= submit_tag t(".unfriend"), class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/posts/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">All posts</a>
  </li>
  <% if user_signed_in? %>
    <li role="presentation">
      <a href="#friend-post" aria-controls="profile" role="tab" data-toggle="tab">Friend posts</a>
    </li>
  <% end %>
</ul>
<div class="tab-content">
  <div role="tabpanel" class="col-xs-12 tab-pane active" id="all">
    <% if user_signed_in? %>
      <div class="col-xs-12">
        <div class="col-xs-3 pull-right">
          <%= link_to new_post_path, class: "btn btn-primary" do %>
            Create post
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </div>
      </div>
    <% end %>
    <% @posts.each do |p| %>
    <div class="col-xs-12">
      <div class="col-xs-1">
        <%= image_tag p.user.avatar.url(:thumb), class: "img-circle", width: 50, height: 50 %>
      </div>
      <div class="col-xs-10">
        <div class="col-xs-12">
          <div class="col-xs-12 nopadding wrap-text">
            <%= link_to p.user.email, user_path(id: p.user_id) %>
            <div class="text-muted">
              <span><%= time_ago_in_words(p.created_at) %> ago</span>
            </div>
          </div>
        </div>
        <div class="col-xs-12">
          <%= link_to post_path(id: p.id) do %>
            <h3 class="nomargin"><b><%= p.title %></b></h3>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12" id="pagiall">
      <%= paginate @posts, theme: "twitter-bootstrap-3", remote: true %>
    </div>
    <div class="col-xs-12">
      <hr>
    </div>
    <% end %>
  </div>
  <div role="tabpanel" class="col-xs-12 tab-pane" id="friend-post">
    <% if user_signed_in? %>
      <div class="col-xs-12">
        <div class="col-xs-3 pull-right">
          <%= link_to new_post_path, class: "btn btn-primary" do %>
            Create post
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </div>
      </div>
      <% @posts_friend.each do |p| %>
      <div class="col-xs-12">
        <div class="col-xs-1">
          <%= image_tag p.user.avatar.url(:thumb), class: "img-circle", width: 50, height: 50 %>
        </div>
        <div class="col-xs-10">
          <div class="col-xs-12">
            <div class="col-xs-12 nopadding wrap-text">
              <%= link_to p.user.email, user_path(id: p.user_id) %>
              <div class="text-muted">
                <span><%= time_ago_in_words(p.created_at) %> ago</span>
              </div>
            </div>
          </div>
          <div class="col-xs-12">
            <%= link_to post_path(id: p.id) do %>
              <h3 class="nomargin"><b><%= p.title %></b></h3>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12" id="pagifriend">
        <%= paginate @posts_friend, theme: "twitter-bootstrap-3", remote: true %>
      </div>
      <div class="col-xs-12">
        <hr>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/index.js.erb
$('#pagiall').html('<%= j paginate @posts, theme: "twitter-bootstrap-3", remote: true %>')
$('#pagifriend').html('<%= j paginate @posts_friend, theme: "twitter-bootstrap-3", remote: true %>')

app/views/posts/new.html.erb
<h3> New Article</h3>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="col-xs-1">
  <div class="col-xs-12 nopadding">
    <% if user_signed_in? && like?(@post.id) %>
      <div class="col-xs-7 nopadding">
        <%= button_to likes_path(@post.id), remote: true, class: "clear" do %>
          <i class="glyphicon glyphicon-thumbs-up liked" id="like_<%= @post.id %>" aria-hidden="true"></i>
        <% end %>
      </div>
    <% else %>
      <div class="col-xs-7 nopadding">
        <%= button_to likes_path(@post.id), remote: true, class: "clear" do %>
          <i class="glyphicon glyphicon-thumbs-up" id="like_<%= @post.id %>" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
    <span id="like_count_<%= @post.id %>"><%= @post.likes.count %></span>
  </div>
</div>
<div class="col-xs-8 nopadding" id="main-path">
  <div class="col-xs-12">
    <div class="col-xs-12">
      <h3><b><%= @post.title %></b></h3>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-6 nopadding text-muted">
        <span class="glyphicon glyphicon-calendar"></span>
        <%= @post.created_at.strftime("%d/%m/%y: %H:%M:%S") %>
      </div>
      <div class="col-xs-6 overview text-muted">
        <span class="glyphicon glyphicon-comment"></span>
        <%= @comments.total_count %>
      </div>
    </div>
    <div class="col-xs-12">
      <%= @post.content.html_safe %>
    </div>
  </div>
  <div class="col-xs-12">
    <hr>
  </div>
  <div class="col-xs-12 nopadding" id="comment_part">
    <div class="col-xs-12">
      <h4><%= t ".comments" %></h4>
    </div>
    <% if user_signed_in? %>
      <div class="col-xs-12">
        <div class="col-xs-12" id="comment_form">
          <%= form_for @comment, remote: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <div class="col-xs-12 nopadding">
              <%= f.text_area :content, class: "form-control" %>
            </div>
            <%= f.submit class: "btn btn-primary pull-right" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-12">
      <div class="col-xs-12" id="comment_list">
        <%= render partial: "posts/comment", collection: @comments, as: :c %>
      </div>
      <div id="paginator">
        <%= paginate @comments, theme: "twitter-bootstrap-3", remote: true %>
      </div>
    </div>
  </div>
</div>
<div class="col-xs-3">
  <div class="col-xs-12">
    <%= image_tag @post.user.avatar.url, class: "img-circle", width: 100, height: 100 %>
  </div>
  <% if user_signed_in? %>
    <% if @post.user.id != current_user.id %>
      <div class="col-xs-12 nopadding" id="friend_button">
        <%= render "posts/friend" %>
      </div>
    <% end %>
  <% end %>
</div>